config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'activities#homepage'

  resources :categories do
    resources :activities
  end

  resources :activities do
    member do
      get :favorite
      get :unfavorite
    end

    resources :bookings, only: %i[create new]
    resources :bookmarks, only: %i[create new]
  end

  resources :bookings do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, only: %i[index show edit update destroy]
  resources :bookmarks, only: %i[index show destroy]
  resources :reviews, only: %i[index destroy]
  resources :activities


  get '/organizer_bookings', to: 'bookings#organizer_index', as: :organizer_bookings
  get '/organizer_activities', to: 'activities#organizer_index', as: :organizer_activities
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :activity
  belongs_to :user

  validates :start_time, presence: true
  validates :status, presence: true
  has_many :reviews, dependent: :nullify

  STATUSES = %w[ Pending Booked Completed ]

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate

  def index
    @bookings = current_user.bookings.all

    # start_date = params.fetch(:start_date, Date.today).to_date
    # @bookings = Booking.where(
    #   start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week
    # )
  end

  def organizer_index
    # @bookings = Booking.all
    @bookings = Booking.joins(:activity).where(activity: { organizer: current_user.organizer })
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @activity = Activity.find(params[:activity_id])
    @booking = Booking.new
  end

  def create
    @activity = Activity.find(params[:activity_id])

    @booking = Booking.create(booking_params)

    @booking.user = User.last
    @booking.activity = @activity

    if @booking.save!
      redirect_to root_path
      flash[:alert] = 'Booking made successfully!'
    else
      render 'activities/show', status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)

    if @booking.save!
      redirect_to organizer_bookings_path
    else
      render 'activities/show', status: :unprocessable_entity
    end
  end

  def destroy
    Booking.destroy(params[:id])
    redirect_to booking_path
  end

  private

  def booking_params
    # :start_time, :end_time
    params.require(:booking).permit(:adult_qty, :child_qty, :start_time, :status)
  end

  def authenticate
    if current_user
      ''
    else
      redirect_to new_user_session_path
      flash[:alert] = 'You must be signed in to do this.'
    end
  end
end

app/views/bookings/_booking.html.erb
<% act = sprintf("%02d", "#{booking.activity.id}") %>
<div class="container-fluid mb-3">
  <div class="card-body">
    <div class="card-review">
      <div class="row m-0">
        <div class="col-lg-4 col-md-6 mb-lg-0 mb-3 p-0 d-flex">
          <%= image_tag(booking.activity.card_image, class: %(img-preview bg-image flex-fill align-self-center), style: %(max-height: 250px;)) %>
        </div>
        <div class="col-lg-8 col-md-6 vstack">
          <span class="h2 fw-bold"><%= booking.activity.name %></span>
          <h6><i class="fa-solid fa-location-dot"></i> <%= booking.activity.address %></h6>
          <h4 class="purple-text fw-bold"><%= booking.start_time.strftime('%A, %d %b %Y') %></h4>
          <h6><i class="fa-solid fa-user-tie"></i></i> Organizer: <%= booking.activity.organizer.user.first_name %> <%= booking.activity.organizer.user.last_name %></h6>
          <h5>
            <span class="badge badge-yellow text-wrap mb-lg-0 my-1"><%= booking.activity.category.name %></span>
            <span class="badge badge-green text-wrap mb-lg-0 my-1">Booking Status: <%= booking.status %></span>
            <span class="badge badge-orange-plain text-wrap mb-lg-0 my-1">Booking ID: <i class="fa-solid fa-location-pin"></i> <%= act %></span>
          </h5>
          <h6>
            <span>Booked for: <%= booking.adult_qty %> adults,</span>
            <span><%= booking.child_qty %> children</span>
          </h6>
          <div class="d-flex flex-wrap justify-content-between">
            <h4 class="fw ms-1">
              Total Price:  <%= number_to_currency((booking.adult_qty * booking.activity.adult_price) + (booking.child_qty * booking.activity.child_price)) %>
            </h1>
            <div class="d-flex d-inline flex-wrap gap-1">
              <%= link_to "Activity details", activity_path(booking.activity), class: %(btn purple-btn-solid d-grid flex-fill fs-6) %>
              <% if booking.status == "Completed" %>
                <%= link_to "Leave a review", new_booking_review_path(booking), class: %(btn purple-btn-outline d-grid flex-fill fs-6) %>
              <% end %>
              <%= link_to "Cancel booking", booking_path(booking), class: %(btn red-btn-solid d-grid flex-fill fs-6), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<h1>Edit your booking status here</h1>

<%= simple_form_for(@booking) do |f| %>

  <%= f.input :status, collection: Booking::STATUSES %>
  <%= f.submit %>

<% end %>

app/views/bookings/index.html.erb
<div class="container-fluid row mt-4 m-0 p-0">

  <div class="m-0 p-0">
    <div class="container-fluid">

    <div class="row">
      <div class="col-md-6">
        <div class="fixation-large m-0 p-0 pe-xl-2">
          <h1 class="fw-bold">Your Bookings</h1>
          <%= month_calendar(events: @bookings) do |date, bookings| %>
            <h6><%= date.day %></h6>

            <% bookings.each do |booking| %>
              <% act = sprintf("%02d", "#{booking.activity.id}") %>
              <%=
                link_to %(<i class="fa-solid fa-location-pin"></i> #{act}).html_safe, activity_path(booking.activity),
                class: %(badge badge-orange text-wrap mb-1),
                title: %(#{booking.activity.name})
              %>
            <% end %>

          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="m-0 p-0">
          <%= render @bookings %>
        </div>
      </div>
    </div>

    </div>
  </div>



</div>


<!-- Previous working code

<div class="container-fluid">
  <h1 class="fw-bold">Your Bookings</h1>
  <div class="d-grid">
    <%= month_calendar(events: @bookings) do |date, bookings| %>
      <h6><%= date.day %></h6>

      <% bookings.each do |booking| %>
        <% act = sprintf("%02d", "#{booking.activity.id}") %>
        <%=
          link_to %(<i class="fa-solid fa-location-pin"></i> #{act}).html_safe, booking_path(booking),
          class: %(badge badge-orange text-wrap mb-2),
          title: %(#{booking.activity.name})
        %>
      <% end %>

    <% end %>
  </div>
</div>

<% @bookings.each do |booking| %>
  <% act = sprintf("%02d", "#{booking.activity.id}") %>
  <div class="container-fluid">
    <div class="card-body">
      <div class="card-review">
        <div class="row m-0">
          <div class="col-lg-3 col-md-6 mb-lg-0 mb-3 p-0 d-flex">
            <%= image_tag(booking.activity.card_image, class: %(img-preview bg-image flex-fill align-self-center), style: %(max-height: 250px;)) %>
          </div>
          <div class="col-lg-9 col-md-6 vstack">
            <span class="h2 fw-bold"><%= booking.activity.name %></span>
            <h6><i class="fa-solid fa-location-dot"></i> <%= booking.activity.address %></h6>
            <h4 class="purple-text fw-bold"><%= booking.start_time.strftime('%A, %d %b %Y') %></h4>
            <h6><i class="fa-solid fa-user-tie"></i></i> Organizer: <%= booking.activity.organizer.user.first_name %></h6>
            <h5>
              <span class="badge badge-yellow text-wrap mb-lg-0 mb-2"><%= booking.activity.category.name %></span>
              <span class="badge badge-green text-wrap mb-lg-0 mb-2">Booking Status: <%= booking.status %></span>
              <span class="badge badge-orange-plain text-wrap mb-lg-0 mb-2">Booking ID: <i class="fa-solid fa-location-pin"></i> <%= act %></span>
            </h5>
            <h6>
              <span>Booked for: <%= booking.adult_qty %> adults,</span>
              <span><%= booking.child_qty %> children</span>
            </h6>
            <div class="d-flex flex-wrap justify-content-between">
              <h1 class="fw-bold">
                <%= number_to_currency((booking.adult_qty * booking.activity.adult_price) + (booking.child_qty * booking.activity.child_price)) %>
              </h1>
              <div class="d-flex d-inline flex-wrap gap-2">
                <%= link_to "Activity details", booking_path(booking), class: %(btn purple-btn-solid d-grid fs-6) %>
                <%= link_to "Leave a review", new_booking_review_path(booking), class: %(btn purple-btn-outline d-grid fs-6) %>
                <%= link_to "Cancel booking", booking_path(booking), class: %(btn red-btn-solid d-grid fs-6), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

-->


<!-- Old code

<div class="container mt-4">
  <h1 class="fw-bold">Your Bookings</h1>
  <div class="simple-calendar">
    <%= month_calendar(events: @bookings) do |date, bookings| %>
      <div>
        <%= date.day %>
      </div>

      <% bookings.each do |booking| %>
        <div class="card-header">
          <div class="card-title">
            <%= link_to booking.activity.name, booking_path(booking) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="">
    <% @bookings.each do |booking| %>
      <div class="card-product">

        <% if booking.activity.photo.key.nil? %>
         <%= image_tag(booking.activity.card_image, class: "img-preview bg-image") %>
        <% else %>
         <%= cl_image_tag booking.activity.photo.key, class: "img-fluid rounded-start image-tag" %>
        <% end %>

           <div class="card-product-infos">
              <h2><%= booking.activity.name %></h2>
              <p><%= booking.start_time.ctime %></p>
              <p><%= booking.activity.category.name %></p>
              <p><%= booking.adult_qty %></p>
              <p><%= booking.child_qty %></p>
              <p><%= booking.status %></p>
              <p><%= booking.activity.organizer.user.first_name %></p>
            </div>
            <div class = "text-end">
              <%= link_to "Details", booking_path(booking), class: %(btn btn-sm), style: "margin-right: 10px; background-color: #00888E; color: white; border-radius: 10px" %>
              <%= link_to "Leave a Review", new_booking_review_path(booking), class: %(btn btn-sm), style: "margin-right: 10px; background-color: #605DEC; color: white; border-radius: 10px" %>
              <%= link_to "Cancel Booking", booking_path(booking), class: "btn btn-sm", style: "margin-right: 10px; background-color: #FF4747; color: white; border-radius: 10px", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
            </div>
      <%# <div>
        <table class="table table-striped table-hover text-center", style="border: black;">
          <thead>
            <tr>
              <div> %>
                <%# <th colspan="10">Activity</th>
                <th colspan="10">Date</th>
                <th colspan="10">Category</th>
                <th colspan="10">Adults</th>
                <th colspan="10">Children</th>
                <th colspan="10">Status</th>
                <th colspan="10">Organizer</th>
                <th colspan="10"></th> %>
              <%# </div>
            </tr>
          </thead> %>
      <div>
    <% end %>
  </div>
</div>

-->

app/views/bookings/new.html.erb
<div class="bg-container">

  <div class="card-trip pb-5">
    <%= image_tag(@activity.card_image, style: "height:400px;width:100%;object-fit:cover; padding-bottom: 20px;") %>
    <div class="card-trip-infos">

      <div class="container">

        <div class="row">
          <div class="col-5">
            <h1><%=@activity.name %></h1>
            <h6>Category: <%=@activity.category.name %></h6 >
            <br>
            <br>
            <h6><%=@activity.address %></h6>
            <p>
Fun filled activities for everyone! Bring your kids and and families to embark at our most popular venue yet. Come here for the the most enriching experience, and leave lasting fulfilled and wanting more!</p>
          </div>
          <div class="col-7">
              <%= simple_form_for [@activity, @booking,] do |f| %>
                <%= f.input :adult_qty %>
                <br>
                <%= f.input :child_qty %>
                <br>
                <%= f.input :start_time, label: "Booking Date" %>
                <br>
                <div class="">
                  <br>
                  <%= link_to "Return", bookings_path, class: "btn btn-outline-secondary fs-6 py-2 w-25" %>
                  <%= f.button :submit, "Submit", class: 'btn btn-outline-primary fs-6 py-2 ms-3 w-25' %>
              <% end %>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>

</div>

app/views/bookings/organizer_index.html.erb
<div>
  <% @bookings.last(6).each do |booking| %>
    <div class="container">
      <div class="row shadow mx-auto mt-3 border" style="border-radius: 20px;">
        <div class="col-4 p-0 m-0">
          <% if booking.activity.photo.key.nil? %>
            <%= image_tag(booking.activity.card_image, class: "img-fluid image-tag", style: "border-top-left-radius: 15px 15px; border-bottom-left-radius: 15px 15px;") %>
          <% else %>
            <%= cl_image_tag booking.activitiy.photo.key, class: "img-fluid rounded-start image-tag", style: "border-top-left-radius: 15px 15px; border-bottom-left-radius: 15px 15px" %>
          <% end %>
        </div>
        <div class="col-8">

          <div class="card-body ps-4 pt-4 pb-4">
            <h2 class="card-text" style="color:black"><strong><%= booking.activity.name %></strong></h2>
            <p class="card-text card-add">Booking From: <%= booking.user.first_name %></p>
            <p class="card-text card-add">Suitable For Ages: <%= booking.activity.age_group %></p>
            <br>
            <br>
            <p class="card-text card-add"><%= link_to booking.activity.address, '#' %></p>
            <p class="card-text card-add">Booking Created: <%= booking.start_time%></p>

            <br>

            <%= simple_form_for(booking) do |f| %>
              <div class="d-flex align-items-center" style="color:black">
                <%= f.input :status, collection: Booking::STATUSES, label: false, wrapper_html: { style: 'margin-bottom: 0 !important' } %>
                <%= f.submit 'Update', class: 'btn btn-primary' %>
              </div>
            <% end %>
            </div>

          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>