config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'activities#homepage'

  resources :categories do
    resources :activities
  end

  resources :activities do
    member do
      get :favorite
      get :unfavorite
    end

    resources :bookings, only: %i[create new]
    resources :bookmarks, only: %i[create new]
  end

  resources :bookings do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, only: %i[index show edit update destroy]
  resources :bookmarks, only: %i[index show destroy]
  resources :reviews, only: %i[index destroy]
  resources :activities


  get '/organizer_bookings', to: 'bookings#organizer_index', as: :organizer_bookings
  get '/organizer_activities', to: 'activities#organizer_index', as: :organizer_activities
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="fix">
  <div style="margin-top: 150px; border-top: 1px solid lightgray">
    <div class="container text-center mt-4 mb-4">
      <div class="row">
        <div class="col" style="font-size: 30px; color: blue;">
          <ul>
            <li><h2 style="margin-bottom: 80%;">KidsTrotter</h2></li>
          </ul>
        </div>
        <div class="col">
          <ul>
            <li class="text-header"><strong>About</strong></li>
            <li>About KidsTrotter</li>
            <li>Careers</li>
            <li>Forum</li>
          </ul>
        </div>
        <div class="col">
          <ul class="">
            <li class="text-header"><strong>Partner with us</strong></li>
            <li>Partnership programs</li>
            <li>Affiliate program</li>
            <li>Community</li>
            <li>Loyality program</li>
          </ul>
        </div>
        <div class="col">
          <ul>
            <li class="text-header"><strong>Support</strong></li>
            <li>Help Center</li>
            <li>Contact us</li>
            <li>Terms of service</li>
            <li>Accessibility</li>
          </ul>
        </div>
        <div class="col">
          <ul>
            <li class="text-header"><strong>Get the app</strong></li>
            <li>Mobile site</li>
            <li>KidsTrotter for Android</li>
            <li>KidsTrotter for iOS</li>
            <li><%= image_tag('playstore.png', class: "store-icons") %></li>
            <li><%= image_tag('appstore.png', class: "store-icons") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <%# footer %>
  <div style="border-top: 1px solid lightgray;">
    <div class="footer container" style="background-color: white">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        © 2022 KidsTrotter Studios
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="sticky-top w-100 navcon navbar navbar-expand-sm navbar-light navbar-lewagon bg-white">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo.png", style: "height: 50px; width: 50px;") %>
      KidsTrotter
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-button" %>
          </li>

        <% elsif current_user.try(:organizer) %>

          <li class="nav-item">
            <%= link_to "Create an Activity", new_activity_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Activities", activities_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Patron List", organizer_bookings_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
             <% if current_user.avatar.attached?%>
              <%= image_tag(current_user.avatar, type: "button", alt: "avatar", class: "avatar", style: "margin-left: 20px; margin-bottom:5px; height: 40px; width: 40px;", id: "avatar", data: { aria_controls: "#kidstrotteroffcanvasadmin", bs_target: "#kidstrotteroffcanvasadmin", bs_toggle: "offcanvas" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% else %>
              <%= image_tag("avatar.png", type: "button", alt: "avatar", class: "avatar", style: "margin-left: 20px; margin-bottom:5px; height: 40px; width: 40px;", id: "avatar", data: { aria_controls: "#kidstrotteroffcanvasadmin", bs_target: "#kidstrotteroffcanvasadmin", bs_toggle: "offcanvas" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% end %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Activities", activities_path, class: "nav-link" %>
          </li class="nav-item">
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookmarks", bookmarks_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.avatar.attached?%>
              <%= image_tag(current_user.avatar, type: "button", alt: "avatar", class: "avatar", style: "margin-left: 20px; margin-bottom:5px; height: 40px; width: 40px;", id: "avatar", data: { aria_controls: "kidstrotteroffcanvas", bs_target: "#kidstrotteroffcanvas", bs_toggle: "offcanvas" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% else %>
              <%= image_tag("avatar.png", type: "button", alt: "avatar", class: "avatar", style: "margin-left: 20px; margin-bottom:5px; height: 40px; width: 40px;", id: "avatar", data: { aria_controls: "kidstrotteroffcanvas", bs_target: "#kidstrotteroffcanvas", bs_toggle: "offcanvas" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% end %>
          </li>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/shared/_offcanvas.html.erb
<div class="offcanvas offcanvas-end overflow-auto canvas-container" data-bs-scroll="true" tabindex="-1" id="kidstrotteroffcanvas" aria-labelledby="kidstrotteroffcanvasLabel">

    <div class="row justify-content-center mt-4 canvas-wrap1 shadow-sm">
      <div class="canvas-avatar col-4">
        <% if current_user.avatar.attached?%>
          <%= image_tag(current_user.avatar, alt: "avatar", class: "avatar", id: "avatar", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% else %>
          <%= image_tag("avatar.png", alt: "avatar", class: "avatar", id: "avatar", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% end %>
      </div>

      <div class='canvas-header col-6'>
        <div class="canvas-text">Logged in as: <%= current_user.first_name.capitalize %></div>
      </div>

      <div class='canvas-header col-2'>
        <button type="button" class="btn p-0 fa-solid fa-xmark fa-2x mt-1" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>


    </div>

    <div class="row justify-content-center mt-4 canvas-wrap2 shadow-sm">
      <div class='canvas-body col-12'>

        <div class="canvas-text">
          <i class="fa-regular fa-star"></i>
          <%= link_to "My Reviews", reviews_path %>
        </div>

        <div class="canvas-text">
          <i class="fa-regular fa-address-card"></i>
          <%= link_to "Edit Profile", edit_user_registration_path %>
        </div>

        <div class="canvas-text">
          <i class="fa-sharp fa-solid fa-square-phone-flip"></i>
          <%= link_to "Help & Support", "#" %>
        </div>

        <div class="canvas-text">
          <i class="fa-regular fa-moon"></i>
          <%= link_to "Display Settings", "#" %>
        </div>

        <div class="canvas-text">
          <i class="fa-solid fa-user-tie"></i>
          <%= link_to "About Us", "#" %>
        </div>

        <div class="canvas-text-last">
          <i class="fa-solid fa-right-from-bracket"></i>
          <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete} %>
        </div>

      </div>
    </div>
</div>

app/views/shared/_offcanvasadmin.html.erb
<div class="offcanvas offcanvas-end overflow-auto canvas-container" data-bs-scroll="true" tabindex="-1" id="kidstrotteroffcanvasadmin" aria-labelledby="kidstrotteroffcanvasadminLabel">

    <div class="row justify-content-center mt-4 canvas-wrap1 shadow-sm">
      <div class="canvas-avatar col-4">
        <% if current_user.avatar.attached?%>
          <%= image_tag(current_user.avatar, alt: "avatar", class: "avatar", id: "avatar", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% else %>
          <%= image_tag("avatar.png", alt: "avatar", class: "avatar", id: "avatar", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% end %>
      </div>

      <div class='canvas-header col-6'>
        <div class="canvas-text">Logged in as: <%= current_user.first_name.capitalize %></div>
      </div>

      <div class='canvas-header col-2'>
        <button type="button" class="btn p-0 fa-solid fa-xmark fa-2x mt-1" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>


    </div>

    <div class="row justify-content-center mt-4 canvas-wrap2 shadow-sm">
      <div class='canvas-body col-12'>

        <div class="canvas-text">
          <i class="fa-regular fa-futbol"></i>
          <%= link_to "Hosted Activities", organizer_activities_path %>
        </div>

        <div class="canvas-text">
          <i class="fa-regular fa-address-card"></i>
          <%= link_to "Edit Profile", edit_user_registration_path %>
        </div>

        <div class="canvas-text">
          <i class="fa-sharp fa-solid fa-square-phone-flip"></i>
          <%= link_to "Help & Support", "#" %>
        </div>

        <div class="canvas-text">
          <i class="fa-regular fa-moon"></i>
          <%= link_to "Display Settings", "#" %>
        </div>

        <div class="canvas-text">
          <i class="fa-solid fa-user-tie"></i>
          <%= link_to "About Us", "#" %>
        </div>

        <div class="canvas-text-last">
          <i class="fa-solid fa-right-from-bracket"></i>
          <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete} %>
        </div>

      </div>
    </div>
</div>