config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'activities#homepage'

  resources :categories do
    resources :activities
  end

  resources :activities do
    member do
      get :favorite
      get :unfavorite
    end

    resources :bookings, only: %i[create new]
    resources :bookmarks, only: %i[create new]
  end

  resources :bookings do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, only: %i[index show edit update destroy]
  resources :bookmarks, only: %i[index show destroy]
  resources :reviews, only: %i[index destroy]
  resources :activities


  get '/organizer_bookings', to: 'bookings#organizer_index', as: :organizer_bookings
  get '/organizer_activities', to: 'activities#organizer_index', as: :organizer_activities
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :activities

  def icon_image
    {
      'Nature' => 'forest-100.png',
      'Wildlife' => 'penguin-100.png',
      'Indoor Playground' => 'playground-100.png',
      'Museums and Exhibitions' => 'museum-100.png',
      'Outdoor Attractions' => 'theme-park-100.png'
    }[name]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category, only: %i[show]

  def index
    @categories = Category.all
    @activities = Activity.all
  end

  def show

    @category = Category.find(params[:id])
    @activities = @category.activities

    # @categories = Category.all
    # @activities = Activity.all

    # check if user searched for anything
    @activities = @activities.search_by_activity_and_category(params[:query]) if params[:query].present?
    # check if user filtered by price
    @activities = @activities.where(require_payment: params[:require_payment]) if params[:require_payment].present? && params[:require_payment] != 'all'
    # check if user filtered by categories
    @activities = @activities.where(category_id: params[:category].to_i) if params[:category].present?
    # check if user filtered by adult price
    if params[:adult_price].present?
      @activities = @activities.order(adult_price: :desc) if params[:adult_price] == "highest"
      @activities = @activities.order(adult_price: :asc) if params[:adult_price] == "lowest"
    end

    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude
      }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
    @map_activities = Activity.all
    @activities = @category.activities
    # @map_activities = Activity.all
  end
end

app/views/categories/show.html.erb
<div class="container">

  <h1><%= @category.name %></h1>
  <div class="form">
    <%= form_with url: category_path(@category), method: :get, class: "d-flex" do %>
      <%= text_field_tag :query, params[:query], class: "form-control search-bar", placeholder: "Search..."%>
      <%= select_tag :require_payment, options_for_select([
        ["All", "all"],
        ["Free", false],
        ["Paid", true]
        ], selected: params[:require_payment],
        )%>
      <%= submit_tag "Search", class: "btn btn-success search-btn" %>
    <% end %>
  </div>
</div>

<div class="container d-flex mb-2">
  <div>
    <div class="card mb-3 h-card" style="max-width: 700px;">
      <% @activities.each do |activity| %>

        <div class="row g-0 s-card icon-container">
          <div class="col-md-4">
            <% if activity.photo.key.nil? %>
              <%= image_tag(activity.card_image, class: "img-fluid rounded-start image-tag") %>
            <% else %>
              <%= cl_image_tag activity.photo.key, class: "img-fluid rounded-start image-tag" %>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><strong><%= activity.name %></strong></h5>
              <p class="card-text card-add">📍<%= link_to activity.address, '#' %></p>
              <p class="card-text card-age">Suitable For Ages: <%= activity.age_group %></p>
              <p class="card-text card-add">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Ut enim ad minim veniam </p>
              <p class="card-trip-pricing card-price">
                <% if activity.adult_price == 0%>
                  Free
                <% else %>
                  From S$<%= sprintf('%.2f', activity.adult_price) %>
                <% end %>
              </p>
              <%= link_to('More details', activity_path(activity), class: "btn purple-btn-solid btn-detail mt-2 fs-6", type: "button", style: "border-radius: 5px; padding: 1px 10px 1px 10px") %>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>

  <div style="width: 700px; height: 500px; float: right; position: sticky; bottom: 1rem;
    align-self: flex-end; margin-top: 15px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>