config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'activities#homepage'

  resources :categories do
    resources :activities
  end

  resources :activities do
    member do
      get :favorite
      get :unfavorite
    end

    resources :bookings, only: %i[create new]
    resources :bookmarks, only: %i[create new]
  end

  resources :bookings do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, only: %i[index show edit update destroy]
  resources :bookmarks, only: %i[index show destroy]
  resources :reviews, only: %i[index destroy]
  resources :activities


  get '/organizer_bookings', to: 'bookings#organizer_index', as: :organizer_bookings
  get '/organizer_activities', to: 'activities#organizer_index', as: :organizer_activities
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  include PgSearch::Model

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookmarks
  has_many :users, through: :bookmarks
  has_many :bookings
  belongs_to :organizer
  belongs_to :category
  has_and_belongs_to_many :age_groups
  has_one_attached :photo
  # has_many :google_images
  acts_as_favoritable

  validates :name, :address, presence: true
  validates :adult_price, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :child_price, numericality: { greater_than_or_equal_to: 0 }, presence: true

  pg_search_scope :search_by_activity_and_category,
                  against: %i[name],
                  associated_against: { category: %i[name] },
                  using: { tsearch: { prefix: true } }

  # pg_search_scope_2 :search_by_activity_and_category,
  #                   against: %i[name],
  #                   associated_against: { category: %i[name] },
  #                   using: { tsearch: { any_word: true } }
  # before_save :update_google_image_urls

  # TODO
  # has_attached :photo

  # def photo_url
  #   photo.attached? ? photo.path : card_image
  # end

  # <img src="#{photo_url}"

  def hero_image_url
    image_urls.first
  end

  def completed?
    true
  end

  def card_image
    { 'Gardens by the Bay' => "Activities/Nature/Gardens by the Bay/_DSC9043.jpg",
      'ORTO' => "Activities/Nature/ORTO/2021-09-28.jpg",
      'Bollywood Farms' => "Activities/Nature/Bollywood Farms/IMG_20190419_093439.jpg",
      "Jacob Ballas Children's Garden" => "Activities/Nature/Jacob Ballas Children's Garden/2021-12-04.jpg",
      'Singapore Botanic Gardens' => "Activities/Nature/Singapore Botanic Gardens/20221027_131105.jpg",
      'Water Play at Clusia Cove' => "Activities/Nature/Water Play at Clusia Cove/2020-03-19.jpg",
      'Singapore Zoo' => "Activities/Wildlife/Singapore Zoo/2021-06-24.jpg",
      'Jurong Bird Park' => "Activities/Wildlife/Jurong Bird Park/2022-08-03.jpg",
      'S.E.A Aquarium' => "Activities/Wildlife/S.E.A Aquarium/SEAA_OOT_3Kids_Layered double Lighten.jpg",
      'Gallop Stable' => "Activities/Wildlife/Gallop Stable/2022-08-06.jpg",
      'The Live Turtle & Tortoise Museum' => "Activities/Wildlife/The Live Turtle & Tortoise Museum/20220711_143804.jpg",
      'Jurong Frog Farm' => "Activities/Wildlife/Jurong Frog Farm/2021-11-28.jpg",
      'Hay Dairies' => "Activities/Wildlife/Hay Dairies/2022-04-01.jpg",
      'Pororo Park Singapore' => "Activities/Indoor Playground/Pororo Park Singapore/2021-01-13.jpg",
      'Superpark Singapore' => "Activities/Indoor Playground/Superpark Singapore/2021-12-12.jpg",
      'Kiztopia Club' => "Activities/Indoor Playground/Kiztopia Club/20210616-Kiztopia-ClubJP-0388_WEB.jpg",
      'Play by Kinderplay' => "Activities/Indoor Playground/Play by Kinderplay/2022-11-09.jpg",
      'Amazonia' => "Activities/Indoor Playground/Amazonia/The Team.jpg",
      'NERF Action Xperience' => "Activities/Indoor Playground/NERF Action Xperience/20190924_NAX_INTERIOR_006.jpg",
      'Tayo Station' => "Activities/Indoor Playground/Tayo Station/NNM_3052.JPG",
      'Paragon Playground' => "Activities/Indoor Playground/Paragon Playground/2018-05-15.jpg",
      "PIP's Playbox" => "Activities/Indoor Playground/PIP's Playbox/IMG_20210821_150839.jpg",
      'Marina Square Playground' => "Activities/Indoor Playground/Marina Square Playground/2019-08-06.jpg",
      'Suntec City Playground' => "Activities/Indoor Playground/Suntec City Playground/Suntec-City-Playground-p-1080.jpg",
      'Singapore Discovery Centre' => "Activities/Museums and Exhibitions/Singapore Discovery Centre/Photo Op at Concourse.jpg",
      '313 Somerset Playground' => "Activities/Indoor Playground/313 Somerset Playground/2022-09-04.jpg",
      'Science Centre Singapore' => "Activities/Museums and Exhibitions/Science Centre Singapore/IMG_20190601_152554.jpg",
      'Lee Kong Chian Natural History Museum' => "Activities/Museums and Exhibitions/Lee Kong Chian Natural History Museum/2022-02-02.jpg",
      'Future World - ArtScience Museum' => "Activities/Museums and Exhibitions/Future World - ArtScience Museum/2019-06-30.jpg",
      'Battlebox' => "Activities/Museums and Exhibitions/Battlebox/IMG_20220903_091809.jpg",
      'National Gallery Singapore' => "Activities/Museums and Exhibitions/National Gallery Singapore/PXL_20220721_041221718.jpg",
      'National Museum of Singapore' => "Activities/Museums and Exhibitions/National Museum of Singapore/2022-10-06.jpg",
      'Air Force Museum' => "Activities/Museums and Exhibitions/Air Force Museum/2018-03-21.jpg",
      'Masak Masak - The Artground' => "Activities/Museums and Exhibitions/Masak Masak - The Artground/IMG_20190813_154451.jpg",
      'Singapore Maritime Gallery' => "Activities/Museums and Exhibitions/Singapore Maritime Gallery/mpa-7834.jpg",
      'Mud Krank' => "Activities/Outdoor Attractions/Mud Krank/20200327_103322.jpg",
      'Skyride at Skyline Luge Sentosa' => "Activities/Outdoor Attractions/Skyride at Skyline Luge Sentosa/IMG_E9638.JPG",
      'The Karting Arena' => "Activities/Outdoor Attractions/The Karting Arena/2019-01-12.jpg",
      'Universal Studios Singapore' => "Activities/Outdoor Attractions/Universal Studios Singapore/IMG_20220704_113421.jpg",
      'SkyHelix Sentosa' => "Activities/Outdoor Attractions/SkyHelix Sentosa/20220416_192119.jpg",
      'Fort Siloso Skywalk' => "Activities/Outdoor Attractions/Fort Siloso Skywalk/2021-12-27.jpg",
      'Coastal Playgrove at East Coast Park' => "Activities/Outdoor Attractions/Coastal Playgrove at East Coast Park/2021-04-09.jpg",
      'Jurassic Mile' => "Activities/Outdoor Attractions/Jurassic Mile/20220314_101946.jpg",
      'Jubilee Park at Fort Canning' => "Activities/Outdoor Attractions/Jubilee Park at Fort Canning/2019-07-07.jpg" }[name]
  end

  # def image_urls
  #   photos = []
  #   photos.present? ? photos : google_images.map(&:url)
  # end

  # def fetch_google_image_urls
  #   thing = CGI.escape(name)
  #   url = URI("https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=#{thing}&inputtype=textquery&fields=place_id%2Cformatted_address%2Cname%2Crating%2Cphotos%2Cgeometry&key=AIzaSyBblxAfyQjITHddg4IYMF77L-PHrfrLW4s")

  #   https = Net::HTTP.new(url.host, url.port)
  #   https.use_ssl = true
  #   request = Net::HTTP::Get.new(url)
  #   read_body = JSON.parse(https.request(request).read_body)

  #   test = read_body.dig("candidates")&.first&.dig("place_id")
  #   url_test = URI("https://maps.googleapis.com/maps/api/place/details/json?place_id=#{test}&fields=name%2Cphotos%2Creviews&key=AIzaSyBblxAfyQjITHddg4IYMF77L-PHrfrLW4s")

  #   https = Net::HTTP.new(url_test.host, url_test.port)
  #   https.use_ssl = true
  #   request = Net::HTTP::Get.new(url_test)
  #   read_body = JSON.parse(https.request(request).read_body)

  #   read_body['result']["photos"].map do |photo|
  #     "https://maps.googleapis.com/maps/api/place/photo?maxwidth=2600&photoreference=#{photo["photo_reference"]}&key=AIzaSyBblxAfyQjITHddg4IYMF77L-PHrfrLW4s"
  #   end
  # end

  # private

  # def update_google_image_urls
  #   fetch_google_image_urls.each do |url|
  #     self.google_images << GoogleImage.create(url: url)
  #   end
  # end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show favorite unfavorite]

  def homepage
    @categories = Category.all
    @activities = Activity.all
  end

  def favorite
    # find the activity
    # favourite the activity with current user
    current_user.favorite(@activity)

    respond_to do |format|
      format.html { redirect_to activities_path }
      format.text { render partial: 'bookmark', formats: :html, locals: { current_user: current_user, activity: @activity }}
    end
  end

  def unfavorite
    # find the activity
    # unfavourite the activity with current user
    current_user.unfavorite(@activity)

    respond_to do |format|
      format.html { redirect_to params[:page] == 'bookmarks' ? bookmarks_path : activities_path }
      format.text { render partial: 'bookmark', formats: :html, locals: { current_user: current_user, activity: @activity }}
    end

    # Bookmark.destroy(params[:id]) #cant find the id after the first deleted due to unique
  end

  def index
    @categories = Category.all
    @activities = Activity.all

    @activities = Activity.near([params["lat"].to_f, params["lon"].to_f], 5) if params["lat"] && params["lon"]

    # check if user searched for anything
    @activities = @activities.search_by_activity_and_category(params[:query]) if params[:query].present?
    # check if user filtered by price
    if params[:require_payment].present? && params[:require_payment] != 'All'
      @activities = @activities.where(require_payment: params[:require_payment])
    end
    # check if user filtered by categories
    @activities = @activities.where(category_id: params[:category].to_i) if params[:category].present?
    # check if user filtered by adult price
    if params[:adult_price].present?
      @activities = @activities.order(adult_price: :desc) if params[:adult_price] == "highest"
      @activities = @activities.order(adult_price: :asc) if params[:adult_price] == "lowest"
    end

    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude
      }
    end

    respond_to do |format|
      format.html
      format.json
    end
  end



  def organizer_index
    @activities = Activity.where(organizer: current_user.organizer)
  end

  def show
    @reviews = Review.all
    @bookings = Booking.all
    @bookmark = Bookmark.new

    @markers = [{
      lat: @activity.latitude,
      lng: @activity.longitude
    }]
  end

  def new
    @activity = Activity.new
  end

  def create
    @categories = Category.all
    @activity = Activity.create(activity_params)
    @activity.organizer = current_user.organizer

    if @activity.save!
      redirect_to root_path
      flash[:alert] = 'Activity has been created successfully!'
    else
      render 'activities/show', status: :unprocessable_entity
    end
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :description, :address, :adult_price, :child_price, :age_group, :category_id, :photo)
  end

  def authenticate
    if current_user
      ''
    else
      redirect_to new_user_session_path
      flash[:alert] = 'You must be signed in to do this.'
    end
  end
end

app/views/activities/_bookmark.html.erb
<% if user_signed_in? && current_user.favorited?(activity) %>

  <% if params[:ret] == 'button' %>

    <%#-------------------------------------
        current user favorited activity
        and is on the activity show page
        so we return a button
    ------------------------------------- %>
      <%= link_to "Bookmarked!", unfavorite_activity_path(@activity, ret: 'button'),
                                 data: { action: "click->bookmark#toggleFavorite" },
                                 class: %(btn purple-btn-solid d-grid fs-6 py-2) if !is_organizer? %>
  <% else %>
    <%#-------------------------------------
        current user favorited activity
        and is on the activity index page
        so we return the bookmark icon
    ------------------------------------- %>
    <%= link_to unfavorite_activity_path(activity), data: { action: "click->bookmark#toggleFavorite" } do %>
      <i class="bi bi-bookmark-fill"></i>
    <% end %>

  <% end %>


<% else %>

  <% if params[:ret] == 'button' %>

    <%#-------------------------------------
        current user unfavorited activity
        and is on the activity show page
        so we return a button
    ------------------------------------- %>
      <%= link_to "Bookmark", favorite_activity_path(@activity, ret: 'button'),
                                 data: { action: "click->bookmark#toggleFavorite" },
                                 class: %(btn purple-btn-solid d-grid fs-6 py-2) if !is_organizer? %>
  <% else %>
    <%#-------------------------------------
        current user unfavorited activity
        and is on the activity index page
        so we return the bookmark icon
    ------------------------------------- %>
    <% if user_signed_in? %>

      <%= link_to favorite_activity_path(activity), data: { action: "click->bookmark#toggleFavorite" } do %>
        <i class="bi bi-bookmark"></i>
      <% end %>

    <% else %>

      <%= link_to new_user_session_path do %>
        <i class="bi bi-bookmark"></i>
      <% end %>

    <% end %>

  <% end %>

<% end %>

app/views/activities/_filtered.html.erb
 <% activities.each do |activity| %>

        <div class="row g-0 s-card">
          <div class="col-md-4">
            <% if activity.photo.key.nil? %>
              <%= image_tag(activity.card_image, class: "img-fluid rounded-start image-tag") %>
            <% else %>
              <%= cl_image_tag activity.photo.key, class: "img-fluid rounded-start image-tag" %>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <button class="card-title" data-action="click->name-button-search-trigger#queryinput" name-button-search-trigger-target="namebtn" style="font-family: Nunito ; font-size: 1.25 rem ; font-weight: bolder; border: none; font-weight: bolder;"><%= activity.name %></button>

              <div class="bookmark-container" data-controller="bookmark">
                <%= render 'bookmark', activity: activity %>
              </div>

              <p class="card-text card-add">📍<%= link_to activity.address, '#' %></p>
              <p class="card-text card-age">Suitable For Ages: <%= activity.age_group %></p>
              <p class="card-text card-add">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</p>
              <p class="card-trip-pricing card-price">
                <% if activity.require_booking == false %>
                  Free
                <% else %>
                  From S$<%= sprintf('%.2f', activity.adult_price) %>
                <% end %>
              </p>
              <%= link_to('More details', activity_path(activity), class: "btn purple-btn-solid btn-detail mt-2 fs-6", type: "button", style: "border-radius: 5px; padding: 1px 10px 1px 10px") %>
              <p class="card-text card-rating">⭐</i>4.9 reviews (2153)</p>

            </div>
          </div>
        </div>

      <% end %>

app/views/activities/show.html.erb
<div class="g-screen-container">
  <div class="card">
    <div class="row g-0">
      <div class="col-md-3">

        <form class="form-purple p-4 m-4">
          <div class="form-outline mb-4">
            <h4 class="fw-bold">Search</h4>
            <label class="form-label">Name of Attraction</label>
            <input type="text" placeholder="Universal Studios" class="form-control" />
          </div>

          <div class="form-outline mb-4">
            <label class="form-label">Visit Date</label>
            <input type="date" class="form-control" />
          </div>

          <div class="row mb-4">
            <div class="col vstack">
              <div class="row">
                <div class="col form-outline mb-4">
                  <label class="form-label">Adults</label>
                  <input type="number" min="0" placeholder="0" class="form-control" />
                </div>
                <div class="col form-outline mb-4">
                  <label class="form-label">Children</label>
                  <input type="number" min="0" placeholder="0" class="form-control" />
                </div>
              </div>
              <!-- Checkbox -->
              <div class="form-check">
                <input id="indoors" class="form-check-input" type="checkbox">
                <label for="indoors" class="form-check-label"> Indoors </label>
              </div>
              <div class="form-check">
                <input id="outdoors" class="form-check-input" type="checkbox">
                <label for="outdoors" class="form-check-label"> Outdoors </label>
              </div>
            </div>
          </div>

          <!-- Submit button -->
          <div class="d-grid">
            <%= link_to "Search",  "", class: %(btn btn-primary form-purple-btn), type: %(submit) %>
          </div>
        </form>

        <form class="form-purple fw-bold p-2 m-4">
          <div id="ww_d048d7a91d69b" v='1.3' loc='id' a='{"t":"responsive","lang":"en","sl_lpl":1,"ids":["wl2912"],"font":"Arial","sl_ics":"one_a","sl_sot":"celsius","cl_bkg":"#B6B2F3","cl_font":"#000000","cl_cloud":"#d4d4d4","cl_persp":"#2196F3","cl_sun":"#FFC107","cl_moon":"#FFC107","cl_thund":"#FF5722","cl_odd":"#0000000a"}'><a href="https://weatherwidget.org/tr/" id="ww_d048d7a91d69b_u" target="_blank">Web Sitesi için Ücretsiz HTML Hava Durumu Widget</a></div><script async src="https://app1.weatherwidget.org/js/?id=ww_d048d7a91d69b"></script>
        </form>

        <form class="form-purple p-4 m-4">
          <div class="form-outline mb-4">
            <h5 class="fw-bold">Package details</h5>
            <h6><span class="d-grid badge badge-pink text-wrap text-start">No cancellation</span></h6>
            <h6><span class="d-grid badge badge-pink text-wrap text-start">Instant confirmation</span></h6>
            <h6><span class="d-grid badge badge-pink text-wrap text-start">Book now for today</span></h6>
          </div>

          <div class="form-outline mb-4">
            <h5 class="fw-bold">Eligibility</h5>
            <h6><span class="d-grid badge badge-green text-wrap text-start">Children aged 0-3 can enter free of charge</span></h6>
          </div>

          <div class="form-outline mb-4">
            <h5 class="fw-bold">Opening hours</h5>
            <h6><span class="d-grid badge badge-yellow text-wrap text-start">Monday to Sunday: 8:30am-6:00pm</span></h6>
          </div>
        </form>

      </div>
      <div class="col-md-9 d-flex align-items-between flex-column">

        <div class="card-body">

          <% booksum = 0 %>

          <% @bookings.each do |booking| %>
            <% if booking.activity_id.eql?(@activity.id) %>
              <% booksum += 1 %>
            <% end %>
          <% end %>

          <div class="card-title fw-bold d-flex align-items-center"><h3><%= @activity.name %></h3>
            <p class="card-text card-age" style="width:150px;padding-top:5px;padding-bottom:5px;margin-left:10px;">Suitable For Ages: <%= @activity.age_group %></p>
            </div>
          <p class="mb-2"><i class="fa-solid fa-star"></i> Reviews: <%= @reviews.count + 3 %> | <i class="fa fa-book"></i> Bookings: <%= booksum %> | <i class="fa-solid fa-location-dot"></i> <%= @activity.address %></p>

          <div class="row">

            <div class="col-lg-8 col-md-12 mb-lg-0 mb-3 d-flex align-items-center">
              <% if @activity.photo.key.nil? %>
                <%= image_tag(@activity.card_image, class: "img-fluid img-preview image-tag flex-fill", style: "height: 600px;") %>
              <% else %>
                <%= cl_image_tag @activity.photo.key, class: "img-fluid img-preview image-tag flex-fill", style: "height: 600px;" %>
              <% end %>
            </div>


            <div class="col-lg-4 mb-lg-0 d-grid">
              <div
                class="img-fluid img-preview image-tag flex-fill"
                style="height: 600px;"
                data-controller="mini-map"
                data-mini-map-markers-value="<%= @markers.to_json %>"
                data-mini-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>

          </div>
        </div>

        <div class="card-body">
          <div class="row">
            <div class="col-lg-8 col-md-12 mb-lg-0 mb-3">
              <div>
                <span class="lh-sm"><p>Southeast Asia's most defining attraction.
                <%= @activity.description %></p></span>
                <%# <span class="h5 lh-sm fw-bold"><p>Suitable For Ages: <%= @activity.age_group %></p></span>
              </div>
            </div>

            <div class="col-lg-4 mb-lg-0">
              <div class="card-activity text-center">

                <div class="d-flex flex-column" style="height: 100%;">
                  <div class="p-2 h5 m-0 fw-bold">Pricing</div>
                  <% price_adult = %(Adult: #{number_to_currency(@activity.adult_price)}) unless @activity.adult_price.zero? %>
                  <% price_child = %(Child: #{number_to_currency(@activity.child_price)}) unless @activity.child_price.zero? %>
                  <% no_charging = %(Free of charge - Booking not required) if @activity.adult_price.zero? && @activity.child_price.zero? %>
                  <div class="p-2 h6 m-0"><span class="fw-bold"><%= price_adult %></span></div>
                  <div class="p-2 h6 m-0"><span class="fw-bold"><%= price_child %></span></div>
                  <div class="p-2 h6 m-0"><span class="fw-bold"><%= no_charging %></span></div>
                  <div class="mt-auto">

                    <div class="row">
                      <div class="col-lg-6 mb-lg-0 mb-3" data-controller="bookmark">
                        <% unless current_user.nil? %>
                          <%=
                            case current_user.favorited?(@activity)
                            when false
                              link_to "Bookmark", favorite_activity_path(@activity, ret: 'button'), data: { action: "click->bookmark#toggleFavorite" }, class: %(btn purple-btn-solid d-grid fs-6 py-2) if !is_organizer?
                            when true
                              link_to "Bookmarked!", unfavorite_activity_path(@activity, ret: 'button'), data: { action: "click->bookmark#toggleFavorite" }, class: %(btn purple-btn-solid d-grid fs-6 py-2) if !is_organizer?
                            end
                          %>
                        <% end %>
                      </div>

                      <div class="col-lg-6 mb-lg-0 mb-3">
                        <% free = link_to "No booking", new_activity_booking_path(@activity), class: %(btn purple-btn-outline d-grid fs-6 py-2 disabled) %>
                        <% paid = link_to "Book Now", new_activity_booking_path(@activity), class: %(btn purple-btn-outline d-grid fs-6 py-2) if !is_organizer? %>
                        <%= @activity.adult_price.zero? && @activity.child_price.zero? ?  free : paid %>
                      </div>
                    </div>

                  </div>
                </div>

              </div>
            </div>

          </div>
        </div>

        <div class="card-body">
          <h2 class="m-0 fw-bold">Most recent reviews</h2>
        </div>

        <% @reviews.each do |review| %>
          <% if review.booking.activity_id.eql?(@activity.id) %>
            <% id = review.id %>
            <% firstName = review.booking.user.first_name %>
            <% lastName = review.booking.user.last_name %>
            <% pic = review.booking.user.avatar.attached? ? review.booking.user.avatar : %(avatar.png) %>
            <% booktime = review.booking.start_time.strftime('%A, %d %b %Y') %>
            <% stars = review.rating %>
            <% comment = review.comment %>
            <% username = %(#{firstName} #{lastName}) %>
            <div class="card-body">
              <div class="card-review">
                <div class="d-flex justify-content-between flex-wrap">
                  <div class="d-inline h5 fw-bold">
                    <span>
                      <%= image_tag(pic, class: %(avatar m-2)) %>
                    </span>
                    <span><%= username %></span>
                    <p class="py-2">
                      <% stars.times do %>
                        <i class="fa-solid fa-star"></i>
                      <% end %>
                      <% (5 - stars).times do %>
                        <i class="fa-regular fa-star"></i>
                      <% end %>
                    </p>
                  </div>
                  <div class="d-inline my-2"><%= booktime %></div>
                </div>
                <p class="m-0"><%= comment %></p>
              </div>
            </div>
          <% end %>
        <% end %>

        <div class="card-body">
          <div class="card-review">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-inline h5 fw-bold">
                <span><img src="https://picsum.photos/80?random=1" class="avatar m-2"></span>
                <span>Monsieur Jean Pierre</span>
                <p class="py-2">
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-regular fa-star"></i>
                </p>
              </div>
              <div class="d-inline my-2">Yesterday</div>
            </div>
            <p class="m-0">Had a wonderful and fun time with my family. Recommended for all to go and have fun.</p>
          </div>
        </div>

        <div class="card-body">
          <div class="card-review">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-inline h5 fw-bold">
                <span><img src="https://picsum.photos/80?random=2" class="avatar m-2"></span>
                <span>Yifei Chen</span>
                <p class="py-2">
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-regular fa-star"></i>
                  <i class="fa-regular fa-star"></i>
                </p>
              </div>
              <div class="d-inline my-2">Yesterday</div>
            </div>
            <p class="m-0">Hassle-free redemption.</p>
          </div>
        </div>

        <div class="card-body">
          <div class="card-review">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-inline h5 fw-bold">
                <span><img src="https://picsum.photos/80?random=3" class="avatar m-2"></span>
                <span>Xiao Ming</span>
                <p class="py-2">
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                  <i class="fa-solid fa-star"></i>
                </p>
              </div>
              <div class="d-inline my-2"><%= Time.now.ctime%></div>
            </div>
            <p class="m-0">Fantastic experience!! You just need the voucher and scan at the entrance. Very easy to use and saves you time and money on purchasing as well.</p>
            <div class="d-flex d-inline gap-4 flex-wrap justify-content-center">
              <div><img src="https://picsum.photos/150?random=1" class="img-round-corners"></div>
              <div><img src="https://picsum.photos/150?random=2" class="img-round-corners"></div>
              <div><img src="https://picsum.photos/150?random=3" class="img-round-corners"></div>
              <div><img src="https://picsum.photos/150?random=4" class="img-round-corners"></div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<!-- Hidden Area

<div class="g-screen-container bg-warning text-center text-light fw-bold">Area below to be deleted</div>
<h1><%= @activity.name %></h1>

<p>ID: <%= @activity.id %></p>
<p>Description: <%= @activity.description %></p>
<p>Adult Price: <%= number_to_currency(@activity.adult_price) %></p>
<p>Location: <%= @activity.address %></p>
<p>Suitable For Ages: <%= @activity.age_group %></p>
<p>Activity Latitude: <%= @activity.latitude %></p>
<p>Activity Longitude: <%= @activity.longitude %></p>



<%= simple_form_for [@activity] do |f| %>
  <%= f.submit %>
<% end %>

-->